# Generated by Django 3.1 on 2020-08-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=50)),
                ('minOrderPrice', models.PositiveIntegerField()),
                ('createdAt', models.DateField()),
                ('storeAddress', models.CharField(max_length=150)),
                ('storeTel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPrice', models.PositiveIntegerField()),
                ('deliveryPrice', models.PositiveIntegerField()),
                ('deliveryPriceList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.store')),
            ],
        ),
    ]
