# Generated by Django 3.1 on 2020-09-26 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('nickName', models.CharField(default='', max_length=30)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeRequest', models.TextField()),
                ('deliveryRequest', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('menuName', models.CharField(max_length=50)),
                ('menuDetail', models.TextField(default='')),
                ('menuPrice', models.PositiveIntegerField(default=0)),
                ('menuOrder', models.PositiveIntegerField(default=0)),
                ('menuImage', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeId', models.CharField(max_length=50)),
                ('status', models.CharField(default='접수대기', max_length=10)),
                ('deliveryTime', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 14, 0, 21, 486850))),
                ('deliveryEndTime', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 14, 0, 21, 486850))),
                ('totalPrice', models.PositiveIntegerField(default=0)),
                ('deliveryPrice', models.PositiveIntegerField(default=0)),
                ('totalPeople', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 14, 0, 21, 486850))),
                ('deliveryType', models.CharField(default='단일배송', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('isDelivery', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(default='', max_length=50)),
                ('storeName', models.CharField(max_length=50)),
                ('minOrderPrice', models.PositiveIntegerField()),
                ('createdAt', models.DateField()),
                ('storeAddress', models.CharField(max_length=150)),
                ('storeTel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionMenu', models.CharField(max_length=50)),
                ('optionName', models.CharField(max_length=50)),
                ('optionPrice', models.PositiveIntegerField(default=0)),
                ('optionOrder', models.PositiveIntegerField(default=0)),
                ('optionList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optionList', to='DeliveryApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=20)),
                ('menuNumber', models.PositiveIntegerField(default=0)),
                ('orderId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='DeliveryApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menuList',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeMenu', to='DeliveryApp.store'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menuList2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryMenu', to='DeliveryApp.deliveryinfo'),
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderPrice', models.PositiveIntegerField(default=0)),
                ('deliveryPrice', models.PositiveIntegerField(default=0)),
                ('deliveryPriceList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.store')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='deliveryInfoList',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveryInfoList', to='DeliveryApp.order'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.appuser'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='', max_length=20)),
                ('orderMethod', models.CharField(default='개인메뉴', max_length=10)),
                ('categoryList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.store')),
            ],
        ),
    ]
