# Generated by Django 3.1 on 2020-08-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ownerName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
