# Generated by Django 3.1 on 2020-09-12 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_auto_20200913_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 0, 0, 38, 835362)),
        ),
    ]
