# Generated by Django 3.1 on 2020-09-01 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0002_store_ownername'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('storeRequest', models.TextField()),
                ('deliveryRequest', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('menuName', models.CharField(max_length=50)),
                ('menuPrice', models.PositiveIntegerField(default=0)),
                ('menuOrder', models.PositiveIntegerField(default=0)),
                ('optionNumber', models.PositiveIntegerField(default=0)),
                ('menuList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuList', to='DeliveryApp.store')),
                ('menuList2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuList2', to='DeliveryApp.deliveryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 22, 55, 44, 662381)),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 22, 55, 44, 662381)),
        ),
        migrations.AddField(
            model_name='order',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='orderPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPeople',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryprice',
            name='deliveryPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliveryprice',
            name='orderPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionMenu', models.CharField(max_length=50)),
                ('optionName', models.CharField(max_length=50)),
                ('optionPrice', models.PositiveIntegerField(default=0)),
                ('optionOrder', models.PositiveIntegerField(default=0)),
                ('optionList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optionList', to='DeliveryApp.menu')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='deliveryInfoList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryInfo', to='DeliveryApp.order'),
        ),
    ]
