# Generated by Django 3.1 on 2020-09-12 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0003_auto_20200913_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='deliveryMethod',
            new_name='orderMethod',
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 0, 17, 45, 258104)),
        ),
    ]
