# Generated by Django 3.1.1 on 2020-09-13 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0004_auto_20200913_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 13, 3, 20, 55, 265048)),
        ),
    ]
