# Generated by Django 3.1 on 2020-09-01 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0004_auto_20200901_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='deliveryInfoList',
        ),
        migrations.RemoveField(
            model_name='deliveryprice',
            name='deliveryPriceList',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menuList',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menuList2',
        ),
        migrations.RemoveField(
            model_name='option',
            name='optionList',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='menuList',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='menuList2', to='DeliveryApp.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='optionList',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='optionList', to='DeliveryApp.option'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryInfoList',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryInfo', to='DeliveryApp.deliveryinfo'),
        ),
        migrations.AddField(
            model_name='store',
            name='deliveryPriceList',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.deliveryprice'),
        ),
        migrations.AddField(
            model_name='store',
            name='menuList',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='menuList', to='DeliveryApp.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 13, 22, 192606)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 13, 22, 192606)),
        ),
    ]
