# Generated by Django 3.1 on 2020-09-24 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0005_auto_20200924_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(default='단일배송', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 1, 32, 51, 370698)),
        ),
    ]
