# Generated by Django 3.1 on 2020-09-01 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0006_auto_20200901_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 16, 35, 615370)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 16, 35, 615370)),
        ),
        migrations.AlterField(
            model_name='store',
            name='menuList',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuList', to='DeliveryApp.menu'),
        ),
    ]
