# Generated by Django 3.1 on 2020-09-01 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0007_auto_20200901_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 21, 30, 560094)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 1, 23, 21, 30, 560094)),
        ),
    ]
