# Generated by Django 3.1 on 2020-09-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0010_auto_20200925_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 17, 28, 48, 662533)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryEndTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 25, 17, 28, 48, 662533)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
