# Generated by Django 3.1 on 2020-09-01 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0011_auto_20200902_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 0, 17, 6, 897447)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 0, 17, 6, 897447)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='접수대기', max_length=10),
        ),
    ]
