# Generated by Django 3.1 on 2020-09-01 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0012_auto_20200902_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderPrice',
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 0, 22, 24, 445860)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 0, 22, 24, 445860)),
        ),
    ]
