# Generated by Django 3.1 on 2020-09-25 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0013_auto_20200925_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 4, 6, 249261)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryEndTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 4, 6, 249261)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 4, 6, 249261)),
        ),
    ]
