# Generated by Django 3.1 on 2020-09-25 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0014_auto_20200925_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusimple',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='DeliveryApp.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 26, 46, 15217)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryEndTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 26, 46, 15217)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 26, 46, 15217)),
        ),
    ]
