# Generated by Django 3.1 on 2020-09-01 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0015_auto_20200902_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='menuList',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='optionList',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryInfoList',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deliveryPriceList',
        ),
        migrations.RemoveField(
            model_name='store',
            name='menuList',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='deliveryInfoList',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveryInfoList', to='DeliveryApp.order'),
        ),
        migrations.AddField(
            model_name='deliveryprice',
            name='deliveryPriceList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryApp.store'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menuList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuList', to='DeliveryApp.store'),
        ),
        migrations.AddField(
            model_name='option',
            name='optionList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optionList', to='DeliveryApp.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 1, 3, 47, 677298)),
        ),
    ]
