# Generated by Django 3.1 on 2020-09-25 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0015_auto_20200925_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusimple',
            name='orderId',
        ),
        migrations.AddField(
            model_name='menusimple',
            name='orderKey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orderId', to='DeliveryApp.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 29, 45, 695102)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryEndTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 29, 45, 694098)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 29, 45, 694098)),
        ),
    ]
