# Generated by Django 3.1 on 2020-09-25 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0016_auto_20200925_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusimple',
            old_name='orderKey',
            new_name='orderId',
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 46, 38, 851849)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryEndTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 46, 38, 851849)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 25, 23, 46, 38, 851849)),
        ),
    ]
