# Generated by Django 3.1 on 2020-09-01 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0016_auto_20200902_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menuDetail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 1, 7, 23, 856432)),
        ),
    ]
