# Generated by Django 3.1 on 2020-09-01 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryApp', '0017_auto_20200902_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuList',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuList', to='DeliveryApp.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.TimeField(default=datetime.datetime(2020, 9, 2, 2, 37, 0, 903078)),
        ),
    ]
